# Generated by Django 3.1.12 on 2025-03-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20250320_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlog',
            old_name='object_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='actionlog',
            old_name='people',
            new_name='who',
        ),
    ]
