# Generated by Django 3.1.12 on 2025-03-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20250320_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
