# Generated by Django 3.1.12 on 2025-04-01 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_auto_20250320_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
