# Generated by Django 3.1.12 on 2025-04-25 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_auto_20250401_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='video_related_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.item'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('portal_link', models.URLField(unique=True)),
                ('yt_link', models.URLField(blank=True, null=True)),
                ('translated_yt_link', models.URLField(blank=True, null=True)),
                ('translation_issue', models.BooleanField(default=False)),
                ('duration', models.DurationField()),
                ('comments', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, default='Video', max_length=10, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_videos', to=settings.AUTH_USER_MODEL)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_videos', to=settings.AUTH_USER_MODEL)),
                ('courses', models.ManyToManyField(related_name='videos', to='courses.Course')),
                ('platform_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_status', to='courses.status')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_status', to='courses.status')),
                ('youtube_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_status', to='courses.status')),
            ],
        ),
        migrations.AddField(
            model_name='actionlog',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.video'),
        ),
    ]
