# Generated by Django 3.1.12 on 2025-04-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20250425_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='localized_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
