# Generated by Django 3.1.12 on 2025-05-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20250501_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='external_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.URLField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
