# Generated by Django 3.1.12 on 2025-05-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20250501_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
