# Generated by Django 3.1.12 on 2025-05-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20250501_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
