# Generated by Django 3.1.12 on 2025-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20250506_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('math(ukraine)', 'Math(Ukraine)'), ('math(khan academy)', 'Math(Khan Academy)'), ('science(khan academy)', 'Science(Khan Academy)'), ('science(ukraine)', 'Science(Ukraine)')], default='math(khan academy)', max_length=69),
        ),
    ]
