# Generated by Django 3.1.12 on 2025-05-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='platform_related_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='youtube_related_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
