# Generated by Django 3.1.12 on 2025-05-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20250508_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='localized_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='portal_link',
            field=models.URLField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='translated_yt_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='yt_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
