# Generated by Django 3.1.12 on 2025-04-08 12:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локація')),
                ('outcome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Підсумок')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Нотатки')),
                ('communication_channel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Канал комунікації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хто проводить')),
            ],
            options={
                'verbose_name': 'Взаємодія',
                'verbose_name_plural': 'Взаємодії',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Назва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Тип взаємодії',
                'verbose_name_plural': 'Типи взаємодії',
            },
        ),
        migrations.CreateModel(
            name='KaRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Роль')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Роль відносно команди',
                'verbose_name_plural': 'Ролі відносно команди',
            },
        ),
        migrations.CreateModel(
            name='SotialRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Роль')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Соціальна роль',
                'verbose_name_plural': 'Соціальні ролі',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефону')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Пошта')),
                ('ka_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.karole', verbose_name='Роль відносно нас')),
                ('sotial_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.sotialrole', verbose_name='Соціальна роль')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персони',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name="Ім'я організації")),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефону')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Пошта')),
                ('people', models.ManyToManyField(blank=True, related_name='institutions', to='crm.User', verbose_name='Персони')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.karole', verbose_name='Роль відносно нас')),
            ],
            options={
                'verbose_name': 'Організація',
                'verbose_name_plural': 'Організації',
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Учасник')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.event', verbose_name='Взаємодія')),
            ],
            options={
                'verbose_name': 'Учасник',
                'verbose_name_plural': 'Учасники',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.eventtype', verbose_name='Тип взаємодії'),
        ),
    ]
