# Generated by Django 3.1.12 on 2025-04-24 10:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='institution',
            name='full_addr',
            field=models.TextField(blank=True, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='institution',
            name='primary_source',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Першоджерело'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_addr',
            field=models.TextField(blank=True, null=True, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_source',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Першоджерело'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='crm.event', verbose_name='Учасник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Основний номер телефону'),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Додатковий номер телефону')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Додатковий номер телефону',
                'verbose_name_plural': 'Додаткові номери телефону',
            },
        ),
        migrations.CreateModel(
            name='ContactInfoInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.CharField(blank=True, max_length=225, null=True, verbose_name='Додаткова контактна інформація')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Додаткова контактна інформація',
                'verbose_name_plural': 'Додаткова контактна інформація',
            },
        ),
    ]
