# Generated by Django 3.1.12 on 2025-04-24 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20250424_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Основний номер телефону'),
        ),
    ]
