# Generated by Django 3.1.12 on 2025-05-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20250426_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Клас організації',
                'verbose_name_plural': 'Класи організації',
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='org_class',
            field=models.ManyToManyField(blank=True, null=True, to='crm.OrgClass', verbose_name='Клас організації'),
        ),
    ]
