# Generated by Django 3.1.12 on 2025-05-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20250501_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgclass',
            name='description',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='org_class',
            field=models.ManyToManyField(blank=True, to='crm.OrgClass', verbose_name='Клас організації'),
        ),
        migrations.AlterField(
            model_name='orgclass',
            name='name',
            field=models.CharField(max_length=128, verbose_name="Ім'я організації"),
        ),
    ]
