# Generated by Django 3.1.12 on 2025-04-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortals',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
