# Generated by Django 3.1.12 on 2025-07-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartviewentry',
            options={'permissions': [], 'verbose_name_plural': 'Charts'},
        ),
    ]
